
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Mar 10 12:50:30 CET 2023
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MOD = 20;
  public static final int MENOS = 18;
  public static final int ENTRE = 19;
  public static final int OPBLOQUE = 10;
  public static final int CALL = 14;
  public static final int RETURN = 15;
  public static final int CLPAR = 7;
  public static final int OPPAR = 6;
  public static final int IDEN = 3;
  public static final int POT = 21;
  public static final int POR = 17;
  public static final int CLBLOQUE = 11;
  public static final int NUM = 12;
  public static final int TYPE = 5;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int DEFFUN = 2;
  public static final int error = 1;
  public static final int ENDLINE = 4;
  public static final int EQ = 8;
  public static final int BOOL = 13;
  public static final int MAS = 16;
}

