
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Feb 19 10:36:24 CET 2023
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MAP = 9;
  public static final int EQQ = 13;
  public static final int MENOS = 17;
  public static final int IDEN = 20;
  public static final int POR = 18;
  public static final int RED = 8;
  public static final int HASH = 11;
  public static final int MEN = 14;
  public static final int LISTAP = 4;
  public static final int FILTER = 10;
  public static final int COMA = 3;
  public static final int EOF = 0;
  public static final int DIV = 19;
  public static final int DIS = 12;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int EQ = 22;
  public static final int PARCIERRE = 7;
  public static final int PARAP = 6;
  public static final int MAY = 15;
  public static final int LISTCIERRE = 5;
  public static final int ENT = 2;
  public static final int MAS = 16;
}

