
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 25 18:27:13 CEST 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 39;
  public static final int POT = 19;
  public static final int CCIERRE = 32;
  public static final int PCIERRE = 30;
  public static final int LCIERRE = 34;
  public static final int LAP = 33;
  public static final int RESTA = 15;
  public static final int TIPEDEF = 7;
  public static final int CAP = 31;
  public static final int INT = 48;
  public static final int PUNTOCOMA = 35;
  public static final int IFELSE = 4;
  public static final int REF = 43;
  public static final int VALPTR = 45;
  public static final int NOT = 26;
  public static final int AND = 20;
  public static final int IGUAL = 36;
  public static final int FUN = 6;
  public static final int OR = 21;
  public static final int CALL = 8;
  public static final int DIV = 17;
  public static final int SUMA = 14;
  public static final int IF = 2;
  public static final int DIST = 25;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int TRUE = 46;
  public static final int error = 1;
  public static final int COMA = 37;
  public static final int MUL = 16;
  public static final int NULL = 42;
  public static final int MENOR = 23;
  public static final int MOD = 18;
  public static final int TIPOINT = 40;
  public static final int PUNTERO = 44;
  public static final int MAYOR = 22;
  public static final int LLEVA = 11;
  public static final int PAP = 29;
  public static final int ELSE = 5;
  public static final int PUNTO = 38;
  public static final int READ = 28;
  public static final int IDEN = 49;
  public static final int WHILE = 3;
  public static final int TIPOBOOL = 41;
  public static final int OPIGUAL = 24;
  public static final int PROC = 12;
  public static final int FALSE = 47;
  public static final int EXEC = 13;
  public static final int STRUCT = 10;
  public static final int PRINT = 27;
}

