
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Feb 10 13:14:11 CET 2023
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int COMA = 3;
  public static final int error = 1;
  public static final int LISTAP = 4;
  public static final int ENT = 2;
  public static final int LISTCIERRE = 5;
  public static final int EOF = 0;
}

