
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Mar 16 00:35:47 CET 2023
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int POT = 21;
  public static final int CCIERRE = 30;
  public static final int PCIERRE = 28;
  public static final int LCIERRE = 32;
  public static final int LAP = 31;
  public static final int RESTA = 17;
  public static final int CAP = 29;
  public static final int INT = 2;
  public static final int PUNTOCOMA = 33;
  public static final int IFELSE = 5;
  public static final int AND = 22;
  public static final int IGUAL = 34;
  public static final int FUN = 8;
  public static final int OR = 23;
  public static final int BOOL = 3;
  public static final int CALL = 9;
  public static final int DIV = 19;
  public static final int SUMA = 16;
  public static final int IF = 4;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int MUL = 18;
  public static final int MENOR = 25;
  public static final int MOD = 20;
  public static final int REAL = 15;
  public static final int MAYOR = 24;
  public static final int LLEVA = 12;
  public static final int ENT = 14;
  public static final int PAP = 27;
  public static final int ELSE = 6;
  public static final int IDEN = 13;
  public static final int WHILE = 7;
  public static final int OPIGUAL = 26;
  public static final int STRUCT = 11;
}

