
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 14 22:48:19 CEST 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 41;
  public static final int POT = 23;
  public static final int CCIERRE = 34;
  public static final int PCIERRE = 32;
  public static final int LCIERRE = 36;
  public static final int LAP = 35;
  public static final int METHODS = 17;
  public static final int RESTA = 19;
  public static final int TIPEDEF = 7;
  public static final int CAP = 33;
  public static final int INT = 50;
  public static final int PUNTOCOMA = 37;
  public static final int IFELSE = 4;
  public static final int REF = 45;
  public static final int VALPTR = 47;
  public static final int AND = 24;
  public static final int IGUAL = 38;
  public static final int FUN = 6;
  public static final int OR = 25;
  public static final int CALL = 8;
  public static final int CLASS = 14;
  public static final int DIV = 21;
  public static final int SUMA = 18;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int TRUE = 48;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int MUL = 20;
  public static final int NULL = 44;
  public static final int MENOR = 27;
  public static final int MOD = 22;
  public static final int TIPOINT = 42;
  public static final int PUNTERO = 46;
  public static final int MAYOR = 26;
  public static final int LLEVA = 11;
  public static final int PAP = 31;
  public static final int ELSE = 5;
  public static final int PUNTO = 40;
  public static final int READ = 30;
  public static final int IDEN = 51;
  public static final int WHILE = 3;
  public static final int TIPOBOOL = 43;
  public static final int OPIGUAL = 28;
  public static final int CONSTRUCTOR = 16;
  public static final int PROC = 12;
  public static final int ATRIBUTES = 15;
  public static final int FALSE = 49;
  public static final int EXEC = 13;
  public static final int STRUCT = 10;
  public static final int PRINT = 29;
}

