
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Fri Apr 07 12:56:11 CEST 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 36;
  public static final int POT = 18;
  public static final int CCIERRE = 29;
  public static final int PCIERRE = 27;
  public static final int LCIERRE = 31;
  public static final int LAP = 30;
  public static final int RESTA = 14;
  public static final int TIPEDEF = 8;
  public static final int CAP = 28;
  public static final int INT = 45;
  public static final int PUNTOCOMA = 32;
  public static final int IFELSE = 5;
  public static final int REF = 40;
  public static final int VALPTR = 42;
  public static final int AND = 19;
  public static final int IGUAL = 33;
  public static final int FUN = 7;
  public static final int OR = 20;
  public static final int CALL = 9;
  public static final int DIV = 16;
  public static final int SUMA = 13;
  public static final int IF = 2;
  public static final int EOF = 0;
  public static final int ASIG = 4;
  public static final int RETURN = 10;
  public static final int TRUE = 43;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int COMA = 34;
  public static final int NULL = 39;
  public static final int MENOR = 22;
  public static final int MOD = 17;
  public static final int TIPOINT = 37;
  public static final int PUNTERO = 41;
  public static final int MAYOR = 21;
  public static final int LLEVA = 12;
  public static final int PAP = 26;
  public static final int ELSE = 6;
  public static final int PUNTO = 35;
  public static final int READ = 25;
  public static final int IDEN = 46;
  public static final int WHILE = 3;
  public static final int TIPOBOOL = 38;
  public static final int OPIGUAL = 23;
  public static final int FALSE = 44;
  public static final int STRUCT = 11;
  public static final int PRINT = 24;
}

