
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 25 20:55:22 CET 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int POT = 20;
  public static final int CCIERRE = 29;
  public static final int PCIERRE = 27;
  public static final int LCIERRE = 31;
  public static final int LAP = 30;
  public static final int RESTA = 16;
  public static final int CAP = 28;
  public static final int INT = 35;
  public static final int PUNTOCOMA = 32;
  public static final int IFELSE = 4;
  public static final int AND = 21;
  public static final int IGUAL = 33;
  public static final int FUN = 7;
  public static final int OR = 22;
  public static final int BOOL = 2;
  public static final int CALL = 8;
  public static final int DIV = 18;
  public static final int SUMA = 15;
  public static final int IF = 3;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int COMA = 34;
  public static final int MENOR = 24;
  public static final int MOD = 19;
  public static final int REAL = 14;
  public static final int MAYOR = 23;
  public static final int LLEVA = 11;
  public static final int ENT = 13;
  public static final int PAP = 26;
  public static final int ELSE = 5;
  public static final int IDEN = 12;
  public static final int WHILE = 6;
  public static final int OPIGUAL = 25;
  public static final int STRUCT = 10;
}

